### PR TITLE
refactor: update code structure + document

### PR DESCRIPTION
**Pull request by thelostone-mc**
#### Description

Screenshot 2019-04-18 at 4 36 41 PM

- all inhertied contracts reside within /inherited & references
  have been updated.
- added README.md
- added comments to Splitter
- added .gitignore
- removed .gitkeep
- updated contract as per [solidity styleguide](https://solidity.readthedocs.io/en/v0.4.24/style-guide.html#function-declaration)
- updated package.json

cc @danlipert / @owocki

### CODE REVIEW

**Review by danlipert — CHANGES_REQUESTED** [review]
Looks good, thanks for fixing it up. Can you fix the imports so that the tests pass? thanks!

**Comment by thelostone-mc** [comment]
I've got no laptop for 2 days ! Will wrap it up after that 👍

**Comment by thelostone-mc** [comment]
@danlipert I updated .embark config and added the build files to `.gitignore`
Test pass & I've attached a screenshot 

Have a look and lemme know if it's alright
Btw: any reason we didn't add `--contracts-only` while creating the app using embark ?

**Comment by danlipert** [comment]
@thelostone-mc I was thinking of making a simple DApp for it in the future so I didn't use `--contracts-only`

**Review by danlipert — APPROVED** [review]

**Pull request merged**
